Repository tsukuba-websci/MPS-TOM-Urnmodel, pull requests merged in 2023-06, with the labels that each got.

#1 ADD: LICENSE
  LICENSE
  README.md
Labels: ready for merge, ready for review, LICENSE

#5 Feature: linter, formatter のconfigとそれを実行するCIワークフローの追加
  .flake8
  .github/workflows/flake8.yml
  pyproject.toml
Labels: CI, enhancement

#3 Feature: GAのコードを公開する
  .github/workflows/flake8.yml
  .gitignore
  .python-version
  Manifest.toml
  data/aps.csv
  data/twitter.csv
  ga/.gitignore
  ga/.gitkeep
  ga/Manifest.toml
  ga/Project.toml
  ga/ga.py
  ga/history2vec.jl
  ga/history2vec.py
  ga/io_utils.py
  ga/julia_initializer.py
  ga/log/.gitkeep
  ga/results/.gitkeep
  ga/results/aps/.gitkeep
  ga/results/synthetic/.gitkeep
  ga/results/twitter/.gitkeep
  ga/run_model.py
  lib/history2vec.jl
  lib/history2vec.py
  lib/julia_initializer.py
  lib/run_model.py
  qd/history2bd/README.md
  qd/history2bd/main.py
  requirements.txt
Labels: enhancement, ready for merge, ga

#8 del: 不要になったgitkeepを削除する
  ga/.gitkeep
  ga/results/.gitkeep
Labels: ready for merge, ga, patch

#10 ADDTIONAL #9
  ga/ga.py
  ga/history2vec.py
  ga/io_utils.py
  ga/main.py
Labels: ga, refactor

#13 poetryの設定によって、GAとQDで共通するモジュールをまとめる
  poetry.lock
  pyproject.toml
Labels: enhancement, ready for merge

#15 Bugfix: historyを適切に更新されるように修正する
  ga/ga.py
  ga/main.py
Labels: bugfix, ready for merge, ga

#17 Feature: 重み付けの方法をシグモイド関数で行うように変更
  ga/ga.py
Labels: enhancement, ga

#14 Feature: QDのコードを公開する
  lib/history2vec.jl
  lib/history2vec.py
  lib/julia_initializer.py
  qd/history2bd/main.py
  qd/main.py
  qd/make_model.py
  qd/synthetic_fitting.py
Labels: enhancement, qd

#18 Bugfix: GAのcsvデータ読み取り順番の修正
  ga/ga.py
  ga/main.py
Labels: bugfix, ga

#20 refactor: history2vecの並列化をlibから呼び出すように変更
  full-search/main.py
  lib/history2vec.py
  qd/main.py
Labels: refactor

#28 Feature: QD,full-searchの出力形式の修正
  full-search/main.py
  make_synthetic_target.jl
  qd/main.py
  qd/synthetic_fitting.py
Labels: enhancement, qd

#27 Pythonのdependencyの管理方法の統一
  poetry.lock
  pyproject.toml
  requirements.txt
Labels: enhancement, ready for merge

#7 Feature: GAの出力形式の修正
  ga/.gitignore
  ga/ga.py
  ga/history2vec.py
  ga/io_utils.py
  ga/main.py
  ga/results/synthetic_target/.gitkeep
  ga/run_model.py
Labels: enhancement, ready for review, ga

#34 Feature: GAの壺モデルの実行を並列化する
  ga/ga.py
Labels: enhancement, ga

#36 Feature: GAのグリッドサーチによるパラメタ探索スクリプトの実装
  ga/ga.py
  ga/grid_search.py
  ga/io_utils.py
  ga/search_best.py
Labels: enhancement, help wanted, ga

#26 [Feature]: GAのドキュメントを公開する
  ga/README.en.md
  ga/README.md
Labels: documentation, ready for review, ga

#41 fix & update: 出力形式の変更
  ga/.gitignore
  ga/ga.py
  ga/grid_search.py
  ga/io_utils.py
  ga/main.py
  qd/main.py
  qd/main_synthetic.py
Labels: enhancement, ga, patch, qd

#42 fix: 合成データのターゲットの誤りを修正
  data/synthetic_target.csv
  make_synthetic_target.jl
Labels: bugfix

#43 Feature: 可視化に必要な前処理
  visualize/preprocessing.py
Labels: enhancement, ga, qd

#48 bugfix: GAのrho,nuの値域を修正
  ga/ga.py
Labels: bugfix, ready for merge, ga

#45 Feature: 可視化するためのスクリプトを公開する
  pyproject.toml
  visualize/STIXTwoText.ttf
  visualize/bar_graph.py
  visualize/radar_chart.py
  visualize/timeline.py
Labels: enhancement

#49 fix: 小さいバグと変更漏れの修正
  ga/io_utils.py
  visualize/bar_graph.py
  visualize/timeline.py
Labels: bugfix

#50 Feature: 可視化を合成データにも対応させる
  .gitignore
  visualize/Manifest.toml
  visualize/Project.toml
  visualize/bar_graph.py
  visualize/radar_chart.py
  visualize/timeline.py
Labels: enhancement

#52 Feature: visualizeディレクトリを整備する
  visualize/README.md
  visualize/graphs/bar_graph.py
  visualize/graphs/radar_chart.py
  visualize/graphs/timeline.py
  visualize/main.py
  visualize/preprocessing.py
  visualize/timeline.py
Labels: documentation, refactor

#53 Feature: 探索スクリプトを整備
  full-search/Manifest.toml
  full-search/Project.toml
  full-search/main.py
  ga/.gitignore
  ga/ga.py
  ga/grid_search.py
  ga/log/.gitkeep
  ga/main.py
  ga/results/aps/.gitkeep
  ga/results/synthetic/.gitkeep
  ga/results/twitter/.gitkeep
  qd/Manifest.toml
  qd/Project.toml
  qd/main.py
  qd/main_synthetic.py
  qd/qd.py
Labels: ga, refactor, qd

#55 Feature: READMEを整備する
  README.md
  full-search/README.md
  ga/README.en.md
  ga/README.md
  qd/README.md
Labels: documentation

#57 Feature: コードの責任の所在を明確にする
  .github/CODEOWNERS
Labels: enhancement, general

#58 Feature: latex形式の表を追加
  visualize/README.md
  visualize/graphs/bar_graph.py
  visualize/graphs/latex_table.py
  visualize/main.py
Labels: enhancement
